# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - variamos-ms-apireference

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: variamos.azurecr.io
        username: ${{secrets.ACRUSERNAME}}
        password: ${{secrets.ACRUSERPASSWORD}}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags:  variamos.azurecr.io/${{secrets.ACRUSERNAME}}//variamos-ms-apireference:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App variamos-ms-apireference in production slot
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'variamos-ms-apireference'
        slot-name: 'production'
        publish-profile: ${{secrets.PRODUCTIONSLOTPUBLISHPROFILE}}
        images: 'variamos.azurecr.io/${{secrets.ACRUSERNAME}}/variamos-ms-apireference:latest'